### ISSUE TITLE
Add an option to authenticate through API key

### ISSUE THREAD

**Issue by eaglesemanation** [jellyfin/jellyfin-apiclient-python#19]
Considering that this is a library, I think it would make sense to support uses where using credentials is not a good fit. One example of such use would be Home Assistant integration: https://github.com/home-assistant/core/issues/95123
I don't think I'll have time to work on this during the next month, so hoping somebody has an interest in working on this. If not - I hope I'll not forget about this and submit a PR later on. Thanks to all contributors for working on this!

**Comment by s-t-e-v-e-n-k** [comment]
I believe this is already supported, and documented -- the Access Token is an API key, and can already be used to authenticate.

**Comment by eaglesemanation** [comment]
Got it, distinction in naming made it a bit confusing. Maybe then README could include a small note clarifying that, but other than that this issue can be closed.

**Comment by s-t-e-v-e-n-k** [comment]
It's not really an API token, like GitHub and other services terms them, since its a JSON object that also includes the server and the username as well. I'm happy to change the wording in the README, what would be clearer than "token"?

**Comment by eaglesemanation** [comment]
Jellyfin explicitly names tokens as "API Keys" in it's UI
![image](https://github.com/jellyfin/jellyfin-apiclient-python/assets/52473614/e0b0f62b-ce85-4998-beab-07d5ff2b4277)
So I would mention that name "token" in this repository directly relates to "API Key" in Jellyfin UI. That way you can keep calling it token (I agree that calling it api key is kind of silly), and avoid confusion at the same time

**Comment by s-t-e-v-e-n-k** [comment]
I have an application that uses a token to authenticate and it does not appear as an API key, so it appears this bug is still valid and missing functionality -- I wasn't aware of that section of the Dashboard in the server UI
