### ISSUE TITLE
Publish updated API on pypi

### ISSUE THREAD

**Issue by j-stienstra** [jellyfin/jellyfin-apiclient-python#47]
Can you publish an updated version of the API on pypi? There seem to be a lot of changes since the last version was published and a number of issues have been reported against the Jellyfin component in Home Assistant that might be caused by using an outdated API.
We would like to update to the latest version but can only do so if a package is available on pypi.

Many thanks

**Comment by iwalton3** [comment]
https://pypi.org/project/jellyfin-apiclient-python/1.10.0/
